### ISSUE TITLE
[1pt] Create app and install basic dependencies - Setup (group task)

### ISSUE THREAD

**Issue by GhausAliKhan** [GhausAliKhan/space-travelers-hub#44]
- Team member:
  - Myself: @GhausAliKhan 
- Kanban board: [Click here](https://github.com/GhausAliKhan/space-travelers-hub/projects/2)

Screenshots from macro lizza for the reason I'm working solo:
  ![image](https://github.com/GhausAliKhan/space-travelers-hub/assets/94997336/c311905f-8b16-4550-907b-2e1a2e313db5)
  ![image](https://github.com/GhausAliKhan/space-travelers-hub/assets/94997336/f54233c2-2d3b-4622-9a6d-c783bbc44fa7)
  ![image](https://github.com/GhausAliKhan/space-travelers-hub/assets/94997336/4a7c24f1-0e51-4068-b0ae-0820d9fc357a)

**Comment by GhausAliKhan** [comment]
![image](https://github.com/GhausAliKhan/space-travelers-hub/assets/94997336/387b841a-9f11-405b-88cb-a5e1d2604506)

**Comment by GhausAliKhan** [comment]
![image](https://github.com/GhausAliKhan/space-travelers-hub/assets/94997336/ad5eac28-c25a-4c18-a2ff-18d8058218c7)

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @GhausAliKhan 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct template is used ✔
- All cards exist ✔


## Required Changes ♻️
- [ ] Since you're the only member for this project please make sure to assign all the cards to yourself as I noticed some cards are not assigned a member as shown below 
  ![image](https://github.com/GhausAliKhan/space-travelers-hub/assets/104968236/c209c5a3-5d8d-4420-aa48-51bd96f943e2)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GhausAliKhan** [comment]
Thank you for your review. All cards have been assigned.

**Comment by LionRouge1** [comment]
Hi @GhausAliKhan, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by LionRouge1** [comment]
Hi @GhausAliKhan, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GhausAliKhan** [comment]
Thank you.
